### ISSUE TITLE
Running in virtualenv

### ISSUE THREAD

**Issue by nianhbg** [f00ale/tellmqtt#1]
Hi

I have tried yours code and it works great :-). And it saved me lot of time

But I can`t get it working on virualenv on raspian stretch its missing modules.

**Comment by f00ale** [comment]
Which command gets an error?
If on the virtualenv call, you might not have the virtualenv package installed. Install it with
```
$ sudo apt-get install python3-virtualenv
```

Then the virtualenv call seems to install python2 by default, so call 
```
$ python3 -m virtualenv -p python3 venv
```
(I will update the documentation on this)

Finally, make sure that you are in the git root directory when running the actual command `python3 -m tellmqtt ...`

**Comment by nianhbg** [comment]
Ok thanks 

I will try this later. You can close this for now.

**Comment by f00ale** [comment]
Ok
